### ISSUE TITLE
这个生成sign的方法还能用吗？为什么我生成的sign不对

### ISSUE THREAD

**Issue by coder30** [wudizhangzhi/HupuApp#11]
params = {
    "nav": "buffer,nba,video,follow,cba,lrw,fitness,stylish,gear,digital",
    "clientId": "40834464",
    "crt": "1548225836112",
    "night": "0",
    "lastTid": "0",
    "stamp": "1548225601",
    "_ssid": "PHVua25vd24gc3NpZD4",
    "isHome": "1",
    "time_zone": "Asia/Shanghai",
    "additionTid": "0",
    "client": "861608045774351",
    "android_id": "c515b866695fe8c3",
    "unfollowTid":"" 
}
这是我使用的参数，生成的sign是7717bc707cfc3fb65ba7dbc80f2c2af3
实际上应该是abb413c2776f04686a3037ede3bfcca5

**Comment by wudizhangzhi** [comment]
我看程序运行正常。应该是还可以用啊 @coder30
